-- Source: MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_SKILLS_TARGET
-- Extracted via GET_DDL() on 2026-09-27

CREATE OR REPLACE TABLE MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_SKILLS_TARGET (
    EMP_ID     NUMBER(38,0),
    ENAME      VARCHAR(100),
    SKILL_ID   NUMBER(38,0),
    SKILL_NAME VARCHAR(100),
    LOAD_TS    TIMESTAMP_NTZ(9)
);
