-- Source: MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_SOURCE
-- Extracted via GET_DDL() on 2026-09-27

CREATE OR REPLACE TABLE MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_SOURCE (
    EMPLOYEE_ID          NUMBER(38,0),
    EMPLOYEE_NAME        VARCHAR(100),
    DEPARTMENT           VARCHAR(100),
    EMPLOYEE_STATUS      VARCHAR(20),
    SALARY               NUMBER(12,2),
    UPDATED_TS           TIMESTAMP_NTZ(9),
    MANAGER_NAME         VARCHAR(100),
    MANAGER_ID           NUMBER(38,0),
    EMPLOYEE_DESIGNATION VARCHAR(100)
);
