-- Source: MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_TARGET
-- Extracted via GET_DDL() on 2026-09-26

CREATE OR REPLACE TABLE MULTI_AGENT_SDLC_POC.DEV.EMPLOYEE_TARGET (
    EMPLOYEE_ID      NUMBER(38,0),
    EMPLOYEE_NAME    VARCHAR(100),
    DEPARTMENT       VARCHAR(100),
    EMPLOYEE_STATUS  VARCHAR(20),
    SALARY           NUMBER(12,2),
    LOAD_TS          TIMESTAMP_NTZ(9)
);
